version: "3"
services:
  auth:
    build: auth/.
    ports:
      - "3000:3000"
    depends_on:
      - auth-database
  auth-database:
    image: postgres
    hostname: auth-postgres-srv
    environment:
      - POSTGRES_PASSWORD=postgres
