version: "3"
services:
  auth:
    build: auth/.
    hostname: auth
    environment:
      - JWT_KEY=${JWT_KEY}
    depends_on:
      - auth-database
  auth-database:
    image: postgres
    hostname: auth-postgres-srv
    environment:
      - POSTGRES_PASSWORD=postgres
  client:
    build: client/.
    ports:
      - "3000:3000"
